#!/usr/bin/env python3
"""Generates the Grafana dashboard ConfigMaps in this folder.

Dashboards are written as Python data so they stay compact and reviewable;
run `python3 gen-dashboards.py` after editing, then `kubectl apply -f .`.
The kube-prometheus-stack Grafana sidecar loads any ConfigMap labelled
grafana_dashboard: "1" (in any namespace it watches; we use monitoring).
"""
import json

DS = {"type": "prometheus", "uid": "${datasource}"}


def tpl_vars(extra):
    v = [{"name": "datasource", "type": "datasource", "query": "prometheus",
          "label": "Prometheus", "current": {}, "hide": 0}]
    for name, query, label in extra:
        v.append({"name": name, "label": label, "type": "query", "datasource": DS,
                  "query": {"query": query, "refId": "v"}, "refresh": 2,
                  "includeAll": True, "multi": True, "allValue": ".*",
                  "current": {"text": "All", "value": "$__all"}, "sort": 1})
    return {"list": v}


class Board:
    def __init__(self, uid, title, tags, variables):
        self.d = {"uid": uid, "title": title, "tags": tags, "schemaVersion": 39,
                  "version": 1, "editable": True, "time": {"from": "now-3h", "to": "now"},
                  "refresh": "30s", "timezone": "browser", "graphTooltip": 1,
                  "templating": tpl_vars(variables), "panels": [],
                  "annotations": {"list": []}}
        self.id, self.x, self.y, self.rowh = 1, 0, 0, 0

    def _place(self, w, h):
        if self.x + w > 24:
            self.x, self.y = 0, self.y + self.rowh
            self.rowh = 0
        pos = {"x": self.x, "y": self.y, "w": w, "h": h}
        self.x += w
        self.rowh = max(self.rowh, h)
        return pos

    def row(self, title):
        if self.x:
            self.x, self.y, self.rowh = 0, self.y + self.rowh, 0
        self.d["panels"].append({"id": self.id, "type": "row", "title": title,
                                 "collapsed": False, "gridPos": {"x": 0, "y": self.y, "w": 24, "h": 1}, "panels": []})
        self.id += 1
        self.y += 1

    def panel(self, title, targets, unit="short", kind="timeseries", w=8, h=8, desc="", thresholds=None):
        p = {"id": self.id, "type": kind, "title": title, "description": desc, "datasource": DS,
             "gridPos": self._place(w, h),
             "targets": [{"refId": chr(65 + i), "datasource": DS, "expr": e, "legendFormat": l,
                          "exemplar": True} for i, (e, l) in enumerate(targets)],
             "fieldConfig": {"defaults": {"unit": unit}, "overrides": []},
             "options": {"legend": {"displayMode": "list", "placement": "bottom"},
                         "tooltip": {"mode": "multi"}}}
        if thresholds:
            p["fieldConfig"]["defaults"]["thresholds"] = {"mode": "absolute", "steps": thresholds}
        if kind == "stat":
            p["options"] = {"reduceOptions": {"calcs": ["lastNotNull"]}, "colorMode": "background"}
        self.d["panels"].append(p)
        self.id += 1

    def configmap(self, name):
        name = name.split("/")[-1]
        body = json.dumps(self.d, indent=1)
        json.loads(body)
        ind = "\n".join("    " + line for line in body.splitlines())
        return (f"# GENERATED by gen-dashboards.py — edit the generator, not this file.\n"
                f"apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {name}\n  namespace: monitoring\n"
                f"  labels:\n    grafana_dashboard: \"1\"\n  annotations:\n    grafana_folder: AI Lab\n"
                f"data:\n  {name}.json: |-\n{ind}\n")


GREEN_RED = [{"color": "green", "value": None}, {"color": "orange", "value": 0.8}, {"color": "red", "value": 0.95}]

# ------------------------------------------------------------------ serving
M = 'model_name=~"$model"'
s = Board("ai-lab-serving", "AI Lab — LLM Serving", ["ai-lab", "vllm"],
          [("model", "label_values(vllm:num_requests_running, model_name)", "Model")])
s.row("Traffic & latency (user-facing)")
s.panel("Requests/s by model", [(f'sum by (model_name) (rate(vllm:request_success_total{{{M}}}[2m]))', "{{model_name}}")], "reqps")
s.panel("TTFT p50 / p95", [
    (f'histogram_quantile(0.50, sum by (le, model_name) (rate(vllm:time_to_first_token_seconds_bucket{{{M}}}[5m])))', "p50 {{model_name}}"),
    (f'histogram_quantile(0.95, sum by (le, model_name) (rate(vllm:time_to_first_token_seconds_bucket{{{M}}}[5m])))', "p95 {{model_name}}")],
    "s", desc="Time to first token = queueing + prefill. Exemplars link to Tempo traces when tracing is on.")
s.panel("Inter-token latency p95", [
    (f'histogram_quantile(0.95, sum by (le, model_name) (rate(vllm:time_per_output_token_seconds_bucket{{{M}}}[5m])))', "TPOT p95 {{model_name}}"),
    (f'histogram_quantile(0.95, sum by (le, model_name) (rate(vllm:inter_token_latency_seconds_bucket{{{M}}}[5m])))', "ITL p95 {{model_name}}")],
    "s", desc="Older vLLM: time_per_output_token; newer: inter_token_latency. One of the two series will be empty.")
s.panel("End-to-end latency p95", [
    (f'histogram_quantile(0.95, sum by (le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket{{{M}}}[5m])))', "{{model_name}}")], "s")
s.panel("Prompt tokens/s", [(f'sum by (model_name) (rate(vllm:prompt_tokens_total{{{M}}}[2m]))', "{{model_name}}")], "short")
s.panel("Generation tokens/s", [(f'sum by (model_name) (rate(vllm:generation_tokens_total{{{M}}}[2m]))', "{{model_name}}")], "short")
s.row("Engine pressure (what autoscaling reacts to)")
s.panel("Running requests per pod", [(f'sum by (pod) (vllm:num_requests_running{{{M}}})', "{{pod}}")])
s.panel("Waiting (queued) requests per pod", [(f'sum by (pod) (vllm:num_requests_waiting{{{M}}})', "{{pod}}")],
        desc="KEDA scales on this. Sustained > 0 means users are queueing.")
s.panel("KV cache usage per pod", [
    (f'max by (pod) (vllm:gpu_cache_usage_perc{{{M}}})', "{{pod}}"),
    (f'max by (pod) (vllm:kv_cache_usage_perc{{{M}}})', "{{pod}}")],
    "percentunit", thresholds=GREEN_RED, desc="Near 1.0 => preemptions/recomputation. Metric renamed in newer vLLM.")
s.panel("Prefix cache hit rate", [
    (f'sum by (model_name) (rate(vllm:prefix_cache_hits_total{{{M}}}[5m])) / sum by (model_name) (rate(vllm:prefix_cache_queries_total{{{M}}}[5m]))', "{{model_name}}"),
    (f'sum by (model_name) (rate(vllm:gpu_prefix_cache_hits_total{{{M}}}[5m])) / sum by (model_name) (rate(vllm:gpu_prefix_cache_queries_total{{{M}}}[5m]))', "{{model_name}} (old names)")],
    "percentunit", desc="Compare routing strategies / LMCache on vs off with this panel.")
s.panel("Preemptions/s", [(f'sum by (model_name) (rate(vllm:num_preemptions_total{{{M}}}[5m]))', "{{model_name}}")])
s.panel("Replicas (engine pods up)", [(f'count by (model_name) (vllm:num_requests_running{{{M}}})', "{{model_name}}")], kind="stat", w=8)

# ------------------------------------------------------------------ gpu
G = 'Hostname=~"$node"'
g = Board("ai-lab-gpu", "AI Lab — GPU Fleet", ["ai-lab", "gpu", "dcgm"],
          [("node", "label_values(DCGM_FI_DEV_GPU_UTIL, Hostname)", "Node")])
g.row("Fleet summary")
g.panel("GPUs reporting", [(f'count(DCGM_FI_DEV_GPU_UTIL{{{G}}})', "")], kind="stat", w=6, h=5)
g.panel("Avg GPU util", [(f'avg(DCGM_FI_DEV_GPU_UTIL{{{G}}}) / 100', "")], "percentunit", kind="stat", w=6, h=5)
g.panel("GPUs idle (<5% util)", [(f'count(DCGM_FI_DEV_GPU_UTIL{{{G}}} < 5) or vector(0)', "")], kind="stat", w=6, h=5,
        thresholds=[{"color": "green", "value": None}, {"color": "orange", "value": 1}])
g.panel("GPUs with an XID", [(f'count(DCGM_FI_DEV_XID_ERRORS{{{G}}} > 0) or vector(0)', "")], kind="stat", w=6, h=5,
        thresholds=[{"color": "green", "value": None}, {"color": "red", "value": 1}])
g.row("Per GPU")
g.panel("GPU utilization", [(f'DCGM_FI_DEV_GPU_UTIL{{{G}}}', "{{Hostname}} gpu{{gpu}}")], "percent",
        desc="'Kernel was running' — coarse. Tensor-active is the honest efficiency metric.")
g.panel("Tensor core active", [(f'DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{{{G}}}', "{{Hostname}} gpu{{gpu}}")], "percentunit",
        desc="Profiling metric; needs DCGM profiling metrics enabled (default in GPU Operator's dcgm-exporter config on datacenter GPUs).")
g.panel("Framebuffer used", [(f'DCGM_FI_DEV_FB_USED{{{G}}} * 1024 * 1024', "{{Hostname}} gpu{{gpu}}")], "bytes",
        desc="vLLM pre-allocates ~gpu_memory_utilization at start, so this is flat for serving.")
g.panel("Power", [(f'DCGM_FI_DEV_POWER_USAGE{{{G}}}', "{{Hostname}} gpu{{gpu}}")], "watt")
g.panel("Temperature", [(f'DCGM_FI_DEV_GPU_TEMP{{{G}}}', "{{Hostname}} gpu{{gpu}}")], "celsius",
        thresholds=[{"color": "green", "value": None}, {"color": "orange", "value": 80}, {"color": "red", "value": 87}])
g.panel("Last XID code per GPU", [(f'DCGM_FI_DEV_XID_ERRORS{{{G}}} > 0', "{{Hostname}} gpu{{gpu}}")],
        desc="Gauge = code of the last XID (0 = none). XID 48/63/64/74/79/94/95 usually mean hardware trouble -> cordon. See reliability/03-gpu-health.")
g.panel("Which pod uses which GPU", [(f'max by (Hostname, gpu, namespace, pod) (DCGM_FI_DEV_GPU_UTIL{{{G}, pod!=""}})', "{{namespace}}/{{pod}} @ {{Hostname}}:{{gpu}}")],
        "percent", w=24, desc="dcgm-exporter attaches pod/namespace labels when kubernetes pod mapping is enabled (GPU Operator default).")

# ------------------------------------------------------------------ scheduling
k = Board("ai-lab-scheduling", "AI Lab — Scheduling (Kueue & autoscaling)", ["ai-lab", "kueue", "keda"],
          [("cq", "label_values(kueue_pending_workloads, cluster_queue)", "ClusterQueue")])
C = 'cluster_queue=~"$cq"'
k.row("Kueue")
k.panel("Pending workloads", [(f'sum by (cluster_queue, status) (kueue_pending_workloads{{{C}}})', "{{cluster_queue}} {{status}}")],
        desc="status=active: waiting for quota; inadmissible: can never fit as configured.")
k.panel("Admitted active workloads", [(f'sum by (cluster_queue) (kueue_admitted_active_workloads{{{C}}})', "{{cluster_queue}}")])
k.panel("GPU quota usage", [
    (f'sum by (cluster_queue) (kueue_cluster_queue_resource_usage{{{C}, resource="nvidia.com/gpu"}})', "used {{cluster_queue}}"),
    (f'sum by (cluster_queue) (kueue_cluster_queue_nominal_quota{{{C}, resource="nvidia.com/gpu"}})', "nominal {{cluster_queue}}")],
    desc="usage > nominal means the queue is borrowing from its cohort.")
k.panel("Admission wait p90", [
    (f'histogram_quantile(0.9, sum by (le, cluster_queue) (rate(kueue_admission_wait_time_seconds_bucket{{{C}}}[30m])))', "{{cluster_queue}}")], "s")
k.panel("Preemptions / evictions", [
    (f'sum by (cluster_queue, reason) (increase(kueue_evicted_workloads_total{{{C}}}[1h]))', "{{cluster_queue}} {{reason}}")])
k.panel("Quota borrowing", [
    (f'sum by (cluster_queue) (kueue_cluster_queue_borrowing_limit{{{C}, resource="nvidia.com/gpu"}})', "{{cluster_queue}} limit")],
    desc="Metric availability depends on Kueue version / metrics.enableClusterQueueResources.")
k.row("Autoscaling (KEDA → HPA)")
k.panel("Current vs desired replicas", [
    ('kube_horizontalpodautoscaler_status_current_replicas{namespace="llm-serving"}', "current {{horizontalpodautoscaler}}"),
    ('kube_horizontalpodautoscaler_status_desired_replicas{namespace="llm-serving"}', "desired {{horizontalpodautoscaler}}")], w=12,
    desc="desired > current for long = pods stuck Pending (no GPUs) or slow cold starts.")
k.panel("GPU requests: allocated vs allocatable", [
    ('sum(kube_pod_container_resource_requests{resource="nvidia_com_gpu"} * on (namespace, pod) group_left() (kube_pod_status_phase{phase="Running"} == 1)) by (namespace)', "{{namespace}}"),
    ('sum(kube_node_status_allocatable{resource="nvidia_com_gpu"})', "allocatable")], w=12)

# ------------------------------------------------------------------ cost
# Written to ../05-cost/ because it depends on OpenCost + the cost recording rules.
c = Board("ai-lab-cost", "AI Lab — Cost per token", ["ai-lab", "cost", "opencost"], [])
c.row("GPU spend")
c.panel("GPU $/h by namespace", [("ai_lab:gpu_cost_per_hour:by_namespace", "{{namespace}}")], "currencyUSD", w=12)
c.panel("GPU $/h by model", [("ai_lab:gpu_cost_per_hour:by_model", "{{model_name}}")], "currencyUSD", w=12)
c.row("Unit economics")
c.panel("$ per 1M output tokens", [("ai_lab:cost_per_1m_output_tokens:by_model", "{{model_name}}")], "currencyUSD", w=12,
        desc="GPU cost of the model's pods / generated tokens. Idle replicas make this explode — that's the point.")
c.panel("$ per 1M total tokens (prompt + output)", [("ai_lab:cost_per_1m_total_tokens:by_model", "{{model_name}}")], "currencyUSD", w=12)
c.panel("Output tokens/h by model", [("ai_lab:output_tokens_per_hour:by_model", "{{model_name}}")], w=12)
c.panel("Gateway token usage by model & type", [("ai_lab:gateway_tokens_per_hour:by_model_type", "{{gen_ai_request_model}} {{gen_ai_token_type}}")], w=12,
        desc="From Envoy AI Gateway gen_ai metrics (names version-dependent).")

for b, name in [(s, "dashboard-ai-lab-serving"), (g, "dashboard-ai-lab-gpu"), (k, "dashboard-ai-lab-scheduling"),
                (c, "../05-cost/dashboard-ai-lab-cost")]:
    with open(f"{name}.yaml", "w") as f:
        f.write(b.configmap(name))
    print("wrote", name)
