#!/usr/bin/env bash
# Emit ONE BackendTrafficPolicy with a token-budget rule per registered tenant.
# Envoy Gateway attaches a single BackendTrafficPolicy per target, so per-tenant
# policies would conflict; this regenerates the combined object from ../tenants/*.env.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
cat <<'YAML'
# GENERATED by tenancy/01-onboard-tenant/render-token-budgets.sh — do not edit.
# Requires Envoy Gateway global rate limiting (WITH_RATELIMIT=true) and
# llmRequestCosts (llm_total_token) on the AIGatewayRoutes.
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: token-budget
  namespace: ai-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ai-gateway
  rateLimit:
    type: Global
    global:
      rules:
YAML
shopt -s nullglob
n=0
for f in "${HERE}"/../tenants/*.env; do
  # shellcheck disable=SC1090
  ( source "$f"
    cat <<YAML
        - clientSelectors:
            - headers:
                - {name: x-tenant-id, type: Exact, value: "${TENANT}"}
          limit: {requests: ${TOKENS_PER_HOUR}, unit: Hour}   # tokens, via cost below
          cost:
            request: {from: Number, number: 0}
            response:
              from: Metadata
              metadata: {namespace: io.envoy.ai_gateway, key: llm_total_token}
YAML
  )
  n=$((n+1))
done
if [[ $n -eq 0 ]]; then
  # rules must not be empty: default budget for requests without a known tenant
  cat <<'YAML'
        - clientSelectors:
            - headers:
                - {name: x-tenant-id, type: Distinct}
          limit: {requests: 100000, unit: Hour}
          cost:
            request: {from: Number, number: 0}
            response:
              from: Metadata
              metadata: {namespace: io.envoy.ai_gateway, key: llm_total_token}
YAML
fi
